version: '3.8'

networks:
  fpl_network: # Define a custom network

services:
  frontend:
    build: ./frontend
    ports:
      - "80:5173"
    restart: always
    networks:
      - fpl_network # Attach frontend to the custom network
      

  backend:
    build: ./server
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres
    networks:
      - fpl_network # Attach backend to the custom network 

  postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    restart: always
    environment:
      POSTGRES_USER: mohammadbakeer320
      POSTGRES_PASSWORD: 1a2b3cMjB(())*
      POSTGRES_DB: postgres
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - fpl_network # Attach postgres to the custom network
