# Railway.toml

# Use Nixpacks to build the project
[build]
builder = "NIXPACKS"

# Specify the root directory where package.json is located
context = "./server"

# Define the build steps for the server application
[build.env]
NODE_ENV = "production"

[build.server]
path = "."
build_command = "npm install"

# Define the deployment process for the backend
[deploy]
start_command = "node index.js"
